const { Pool } = require("pg");
const bcrypt = require("bcryptjs");
require("dotenv").config();

let pool;

function getDatabaseConfig() {
  const connectionString = process.env.DATABASE_URL;

  if (!connectionString) {
    throw new Error("Missing required environment variable: DATABASE_URL");
  }

  const sslEnabled =
    process.env.DATABASE_SSL === "true" ||
    (process.env.NODE_ENV === "production" && process.env.DATABASE_SSL !== "false");

  return {
    connectionString,
    max: 10,
    ssl: sslEnabled ? { rejectUnauthorized: false } : false,
  };
}

function getPool() {
  if (!pool) {
    pool = new Pool(getDatabaseConfig());
  }

  return pool;
}

function generateCode(length = 6) {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "";
  for (let i = 0; i < length; i++) {
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  return code;
}

async function initDb() {
  const db = getPool();

  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name       VARCHAR(100) NOT NULL,
      email      VARCHAR(150) NOT NULL UNIQUE,
      password   VARCHAR(255) NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  // Migration: drop role column/constraint if exists
  await db.query(`ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check`);
  await db.query(`ALTER TABLE users DROP COLUMN IF EXISTS role`);

  await db.query(`
    CREATE TABLE IF NOT EXISTS quizzes (
      id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title       VARCHAR(200) NOT NULL,
      description TEXT,
      code        VARCHAR(8) UNIQUE,
      created_at  TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  // Migrations
  await db.query(`ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS code VARCHAR(8) UNIQUE`);
  await db.query(`ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id) ON DELETE SET NULL`);

  // Backfill: assign codes to quizzes that don't have one
  const noCode = await db.query("SELECT id FROM quizzes WHERE code IS NULL");
  for (const row of noCode.rows) {
    let code, attempts = 0;
    do {
      code = generateCode();
      const exists = await db.query("SELECT id FROM quizzes WHERE code = $1", [code]);
      if (exists.rows.length === 0) break;
    } while (++attempts < 10);
    await db.query("UPDATE quizzes SET code = $1 WHERE id = $2", [code, row.id]);
  }
  if (noCode.rows.length > 0) console.log(`[DB] Backfilled codes for ${noCode.rows.length} quizzes`);

  // Backfill: assign orphan quizzes (created_by NULL) to first user
  const orphans = await db.query(
    `UPDATE quizzes SET created_by = (SELECT id FROM users ORDER BY id LIMIT 1)
     WHERE created_by IS NULL AND EXISTS (SELECT 1 FROM users)
     RETURNING id`
  );
  if (orphans.rows.length > 0) console.log(`[DB] Assigned ${orphans.rows.length} orphan quizzes`);

  await db.query(`
    CREATE TABLE IF NOT EXISTS questions (
      id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      quiz_id    INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
      question   TEXT NOT NULL,
      answers    JSONB NOT NULL,
      correct    INTEGER NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS quiz_attempts (
      id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      quiz_id    INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
      score      INTEGER NOT NULL,
      total      INTEGER NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  console.log("[DB] PostgreSQL tables are ready");
  await seedData(db);
  console.log("[DB] Connected to PostgreSQL");
}

async function seedData(db) {
  const hash = await bcrypt.hash("123456", 10);
  await db.query(
    `INSERT INTO users (name, email, password)
     VALUES ($1, $2, $3)
     ON CONFLICT (email) DO NOTHING`,
    ["Demo", "admin@gmail.com", hash]
  );

  const countResult = await db.query("SELECT COUNT(*)::int AS count FROM quizzes");
  if (countResult.rows[0].count > 0) return;

  await seedQuiz(db, "React Quiz", "Kiem tra kien thuc React cua ban", [
    ["React la gi?", ["Framework JavaScript", "Thu vien JavaScript", "Database", "Ngon ngu lap trinh"], 1],
    ["JSX dung de lam gi?", ["Mo ta giao dien UI", "Ket noi server", "Quan ly database", "Xu ly CSS"], 0],
    ["Hook nao dung de quan ly state?", ["useEffect", "useRef", "useState", "useContext"], 2],
    ["useEffect duoc dung de lam gi?", ["Quan ly state", "Xu ly side effects", "Tao component", "Dinh nghia style"], 1],
    ["Props trong React la gi?", ["Bien noi bo", "Du lieu truyen tu cha sang con", "CSS class", "Event handler"], 1],
  ]);

  await seedQuiz(db, "JavaScript Quiz", "Kiem tra kien thuc JavaScript co ban", [
    ["JavaScript la ngon ngu loai gi?", ["Compiled", "Interpreted", "Assembly", "Machine code"], 1],
    ["Tu khoa khai bao bien khong thay doi?", ["var", "let", "const", "static"], 2],
    ["typeof null tra ve gi?", ["null", "undefined", "object", "string"], 2],
    ["Arrow function xuat hien o phien ban nao?", ["ES3", "ES5", "ES6", "ES8"], 2],
    ["Promise.all() lam gi?", ["Chay tuan tu", "Chay dong thoi, cho tat ca xong", "Huy tat ca", "Chi chay dau tien"], 1],
  ]);

  await seedQuiz(db, "HTML & CSS Quiz", "Kiem tra kien thuc HTML va CSS", [
    ["HTML viet tat cua gi?", ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Markup Language", "Home Tool Markup Language"], 0],
    ["The nao tao lien ket trong HTML?", ["<link>", "<a>", "<href>", "<url>"], 1],
    ["CSS viet tat cua gi?", ["Cascading Style Sheets", "Creative Style System", "Computer Style Sheets", "Colorful Style Sheets"], 0],
    ["Thuoc tinh CSS doi mau chu?", ["font-color", "text-color", "color", "foreground-color"], 2],
    ["display: flex dung de lam gi?", ["An element", "Tao layout flexbox", "Them animation", "Dat vi tri tuyet doi"], 1],
  ]);

  console.log("[DB] Seed data created");
}

async function seedQuiz(db, title, description, questions) {
  const code = generateCode();
  const quizResult = await db.query(
    "INSERT INTO quizzes (title, description, code) VALUES ($1, $2, $3) RETURNING id",
    [title, description, code]
  );
  const quizId = quizResult.rows[0].id;

  for (const [question, answers, correct] of questions) {
    await db.query(
      "INSERT INTO questions (quiz_id, question, answers, correct) VALUES ($1, $2, $3, $4)",
      [quizId, question, JSON.stringify(answers), correct]
    );
  }
}

module.exports = { getPool, initDb, generateCode };
